### ISSUE TITLE
Registro de clientes

### ISSUE THREAD

**Issue by flexystock** [flexystock/backapp#20]
Se necesita implementar:
Tabla Business Group para el grupo empresarial en caso de que lo necesite el cliente
Tabla 'relations_user_client' para relacionar Clientes, Grupo Empresarial, usuario y perfil
Envío de verificación de cuenta de correo
Añadir campo 'verify_email' tabla User para la verificación del mail 
Añadir campo 'profile' para identificar el tipo de perfil del usuario
Tabla 'profiles' para los diferentes perfiles de los usuarios

**Comment by FlexyStockFront** [comment]
Estos serían los distintos datos que nos interesaría guardar sobre los usuarios, que son las personas que se registrarían como dueños o gestores de la empresa:

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL, 
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    role VARCHAR(50) NOT NULL, -- (e.g., Owner, Manager)
    document_type VARCHAR(50), -- (e.g., DNI, Passport)
    document_number VARCHAR(50),
    timezone VARCHAR(50) NOT NULL,
    language VARCHAR(50) NOT NULL,
    preferred_contact_method VARCHAR(50), -- (e.g., Email, Phone)
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    security_question VARCHAR(255),
    security_answer VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

Estos serían los datos interesantes sobre la empresa que se va a registrar:

CREATE TABLE companies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL, -- Foreign Key to users
    company_name VARCHAR(255) NOT NULL,
    business_type VARCHAR(100) NOT NULL, -- (e.g., Retail, Wholesale)
    nif_cif VARCHAR(50) UNIQUE NOT NULL, -- Fiscal ID
    foundation_date DATE,
    fiscal_address VARCHAR(255) NOT NULL,
    physical_address VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    company_phone VARCHAR(20) NOT NULL,
    company_email VARCHAR(255) UNIQUE NOT NULL,
    number_of_employees INT,
    industry_sector VARCHAR(100),
    average_inventory_volume DECIMAL(10,2), -- e.g., estimated number of products
    currency VARCHAR(10), -- e.g., EUR, USD
    preferred_payment_methods VARCHAR(255),
    operation_hours VARCHAR(255),
    has_multiple_warehouses BOOLEAN DEFAULT FALSE,
    annual_sales_volume DECIMAL(15,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
